In [1]:
import pandas as pd
import numpy as np

In [14]:
my_array = np.ones(3, dtype=([('foo', int), ('bar', float)]))

In [19]:
print(my_array['foo'])

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [15]:
print(my_array)

[(1, 1.) (1, 1.) (1, 1.)]


In [16]:
my_array = np.ones(3, dtype=(int))
print(my_array)                             

[1 1 1]


In [17]:
print(my_array)

[1 1 1]


In [18]:
print(my_array['foo'])

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [4]:
my_array2 = my_array.view(np.recarray)
print(my_array2.foo)

[1 1 1]


In [20]:
my_array = np.ones(3, dtype=([('foo', int), ('bar', float)]))


In [21]:
print(my_array['foo'])


[1 1 1]


In [22]:
print(my_array['bar'])


[1. 1. 1.]


In [23]:
my_array2 = my_array.view(np.recarray)


In [24]:
print(my_array2)

[(1, 1.) (1, 1.) (1, 1.)]


In [25]:
print(my_array2.foo)


[1 1 1]


In [26]:
data = np.array([['','Col1','Col2'],

SyntaxError: incomplete input (2931746524.py, line 1)

In [27]:
data = np.array([['','Col1','Col2'],
                ['Row1',1,2],
                ['Row2',3,4]])

In [29]:
data

array([['', 'Col1', 'Col2'],
       ['Row1', '1', '2'],
       ['Row2', '3', '4']], dtype='<U11')

In [30]:
pd.DataFrame(
    data=data[1:, 1:], # Extracts only the numeric data (excluding headers)
    index=data[1:, 0], # Uses the first column (Row1, Row2) as the index
    columns=data[0, 1:] # Uses the first row (Col1, Col2) as column names
)


Col1 Col2
Row1    1    2
Row2    3    4

In [ ]:
Breaking it down:

data[1:, 1:]:
Extracts the data values ([[1, 2], [3, 4]]), excluding row/column labels.
index=data[1:, 0]:
Extracts the row index (['Row1', 'Row2']).
columns=data[0, 1:]:
Extracts the column names (['Col1', 'Col2']).

In [34]:
df = pd.read_excel("Data.xlsx")

In [35]:
print(df.head())


   Unnamed: 0           Unnamed: 1      Unnamed: 2  Unnamed: 3 Unnamed: 4  \
0         NaN                 DATE            NAME    DESCRIBE      DEBIT   
1         NaN  2024-02-01 00:00:00        Merhawit  Healthcare     370000   
2         NaN  2024-02-01 00:00:00  Abiel G/Meskel    Forklift     400000   
3         NaN  2024-02-01 00:00:00  Adhanom Tesfay    Computer     250000   
4         NaN  2024-02-01 00:00:00    Bahlbi Guesh    Forklift     200000   

  Unnamed: 5  
0     CREDIT  
1          0  
2          0  
3          0  
4        NaN  


In [39]:
df.shape

(11, 6)

In [40]:
df.info

<bound method DataFrame.info of     Unnamed: 0           Unnamed: 1              Unnamed: 2  Unnamed: 3  \
0          NaN                 DATE                    NAME    DESCRIBE   
1          NaN  2024-02-01 00:00:00                Merhawit  Healthcare   
2          NaN  2024-02-01 00:00:00          Abiel G/Meskel    Forklift   
3          NaN  2024-02-01 00:00:00          Adhanom Tesfay    Computer   
4          NaN  2024-02-01 00:00:00            Bahlbi Guesh    Forklift   
5          NaN  2024-02-01 00:00:00        Natnael Yohannes   Excavator   
6          NaN  2024-02-01 00:00:00           Yosab solomon   Excavator   
7          NaN  2024-02-01 00:00:00            Enginer Fred     Expense   
8          NaN  2024-02-01 00:00:00        Water for office     Expense   
9          NaN  2024-02-01 00:00:00     Awet wood transport     Expense   
10         NaN  2024-03-01 00:00:00  Muyenga site transport     Expense   

   Unnamed: 4 Unnamed: 5  
0       DEBIT     CREDIT  
1      370000

In [41]:
df.describe


<bound method NDFrame.describe of     Unnamed: 0           Unnamed: 1              Unnamed: 2  Unnamed: 3  \
0          NaN                 DATE                    NAME    DESCRIBE   
1          NaN  2024-02-01 00:00:00                Merhawit  Healthcare   
2          NaN  2024-02-01 00:00:00          Abiel G/Meskel    Forklift   
3          NaN  2024-02-01 00:00:00          Adhanom Tesfay    Computer   
4          NaN  2024-02-01 00:00:00            Bahlbi Guesh    Forklift   
5          NaN  2024-02-01 00:00:00        Natnael Yohannes   Excavator   
6          NaN  2024-02-01 00:00:00           Yosab solomon   Excavator   
7          NaN  2024-02-01 00:00:00            Enginer Fred     Expense   
8          NaN  2024-02-01 00:00:00        Water for office     Expense   
9          NaN  2024-02-01 00:00:00     Awet wood transport     Expense   
10         NaN  2024-03-01 00:00:00  Muyenga site transport     Expense   

   Unnamed: 4 Unnamed: 5  
0       DEBIT     CREDIT  
1      3700

In [42]:
df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6]]))

# Use the `shape` property
print(df.shape)

# Or use the `len()` function with the `index` property
print(len(df))

(2, 3)
2


In [43]:
# Take a 2D array as input to your DataFrame 
my_2darray = np.array([[1, 2, 3], [4, 5, 6]])
print(pd.DataFrame(my_2darray))

# Take a dictionary as input to your DataFrame 
my_dict = {1: ['1', '3'], 2: ['1', '2'], 3: ['2', '4']}
print(pd.DataFrame(my_dict))

# Take a DataFrame as input to your DataFrame 
my_df = pd.DataFrame(data=[4,5,6,7], index=range(0,4), columns=['A'])
print(pd.DataFrame(my_df))

# Take a Series as input to your DataFrame
my_series = pd.Series({"Belgium":"Brussels", "India":"New Delhi", "United Kingdom":"London", "United States":"Washington"})
print(pd.DataFrame(my_series))

   0  1  2
0  1  2  3
1  4  5  6
   1  2  3
0  1  1  2
1  3  2  4
   A
0  4
1  5
2  6
3  7
                         0
Belgium           Brussels
India            New Delhi
United Kingdom      London
United States   Washington
